AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Layout/EndOfLine:
  EnforcedStyle: lf

Naming/MethodParameterName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Enabled: false
